In [1]:
import pandas as pd

In [4]:
khis = pd.read_csv('C:\\Users\\Melvin M Shajan\\Desktop\\data_csv\\khis_kajiado_with_coords.csv')
khis.head(5)

,facility_name,orgUnit,orgUnit_level,dataElement_name,dataElement_code,dataElement,dx_type,period,value,County,Subcounty,Ward,uid_record,Latitude,Longitude
0,amboseli dispensary,HzKPLEISiy4,5,Brucellosis,NaN,nb9cfWgxYFc,dataElement,202202,1,kajiado county,loitokitok sub county,Entonet/Lenkism Ward,HzKPLEISiy4_nb9cfWgxYFc_202202,-2.74492,37.3667
1,amboseli dispensary,HzKPLEISiy4,5,MOH 711 MUAC 6 - 59 months Normal (Green),NaN,BZbUjXynxfr,dataElement,202202,24,kajiado county,loitokitok sub county,Entonet/Lenkism Ward,HzKPLEISiy4_BZbUjXynxfr_202202,-2.74492,37.3667
2,amboseli dispensary,HzKPLEISiy4,5,MOH 711 Live birth,NaN,UqKC1DJnymn,dataElement,202203,6,kajiado county,loitokitok sub county,Entonet/Lenkism Ward,HzKPLEISiy4_UqKC1DJnymn_202203,-2.74492,37.3667
3,amboseli dispensary,HzKPLEISiy4,5,MOH 711 MUAC 6 - 59 months Normal (Green),NaN,BZbUjXynxfr,dataElement,202203,48,kajiado county,loitokitok sub county,Entonet/Lenkism Ward,HzKPLEISiy4_BZbUjXynxfr_202203,-2.74492,37.3667
4,amboseli dispensary,HzKPLEISiy4,5,MOH 711 MUAC 6 - 59 months Severe (Red),NaN,sTjfhcH5iXK,dataElement,202203,1,kajiado county,loitokitok sub county,Entonet/Lenkism Ward,HzKPLEISiy4_sTjfhcH5iXK_202203,-2.74492,37.3667

In [5]:
prompts = pd.read_csv('C:\\Users\\Melvin M Shajan\\Desktop\\data_csv\\prompts_no_duplicates (1).csv')
prompts.head(5)

,facility_name,Date/Time Opened,Intent,Intent_Count,County,Subcounty,Latitude,Longitude,Ward
0,amboseli dispensary,2022-07-13 09:28:00,pain_back_butt,1,kajiado county,loitokitok sub county,-2.74492,37.3667,Entonet/Lenkism Ward
1,amboseli dispensary,2022-07-13 09:29:00,pain_back_butt,1,kajiado county,loitokitok sub county,-2.74492,37.3667,Entonet/Lenkism Ward
2,amboseli dispensary,2022-07-13 11:30:00,medication_general,1,kajiado county,loitokitok sub county,-2.74492,37.3667,Entonet/Lenkism Ward
3,amboseli dispensary,2022-07-14 11:22:00,intercourse,1,kajiado county,loitokitok sub county,-2.74492,37.3667,Entonet/Lenkism Ward
4,amboseli dispensary,2022-07-15 09:56:00,heartburn,1,kajiado county,loitokitok sub county,-2.74492,37.3667,Entonet/Lenkism Ward